trigger:
- main

pool:
  name: shivamPool

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    displayName: 'Call GET Operation and Save Response'
    inputs:
      targetType: 'inline'
      script: |
        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl)
        echo "JSON Response: $jsonResponse"
        # Save response to a file for Python script to read
        echo "$jsonResponse" > $(Build.ArtifactStagingDirectory)/response.json

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Python Script'
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: 'manipulate_json.py'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: Bash@3
    displayName: 'Run Python Script'
    inputs:
      targetType: 'inline'
      script: '/usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py'
