trigger:
- main

pool:
  name: shivamPool

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    displayName: 'Call GET Operation and Save Response'
    inputs:
      targetType: 'inline'
      script: |
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        jsonResponse=$(curl -s $apiUrl)
        echo "JSON Response: $jsonResponse"

  - task: CopyFiles@2
    displayName: 'Copy response.json to Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'response.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'responseArtifacts'
      publishLocation: 'pipeline'

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      artifact: 'responseArtifacts'
      path: $(Build.ArtifactStagingDirectory)

  - task: Bash@3
    displayName: 'List Contents of Staging Directory'
    inputs:
      targetType: 'inline'
      script: 'ls -R $(Build.ArtifactStagingDirectory)'

  - task: Bash@3
    displayName: 'Print Content of response.json'
    inputs:
      targetType: 'inline'
      script: 'cat $(Build.ArtifactStagingDirectory)/response.json'

  - task: Bash@3
    displayName: 'Run Python Script'
    inputs:
      targetType: 'inline'
      script: '/usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py'
