trigger:
- main

pool:
  name: shivamPool

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl)
        echo "JSON Response: $jsonResponse"
        # Save response to a file for Python script to read
        echo "$jsonResponse" > response.json

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Execute Python script directly
        /usr/bin/python3 -c "import json
import datetime

# Read JSON from file
with open('response.json', 'r') as file:
    data = json.load(file)

# Manipulate data
timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
data['title'] = f'Updated Title - {timestamp} shivamData'

# Save manipulated data back to file
with open('manipulatedResponse.json', 'w') as file:
    json.dump(data, file, indent=2)

# Print manipulated data
print(f'Manipulated JSON Response: {json.dumps(data, indent=2)}')"
