# Starter pipeline

trigger:
- main

pool:
  name: shivamPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo $(System.DefaultWorkingDirectory)
  displayName: 'Print Default Working Directory'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: OwaspZapScan@0
  inputs:
    ZapApiUrl: 'http://localhost:9090'
    ZapApiKey: 'shivam1234'
    TargetUrl: 'https://qa2-cpx.skan.ai/'
    ExecuteAjaxSpiderScan: true
    ExecuteSpiderScan: true
    MaxChildrenToCrawl: '2'
    ExecuteOpenApiScan: false
