parameters:
- name: agentPoolName
  type: object
  values:
  - 'shivamPool'
  - 'otherPool'

- name: apiUrl
  type: object
  values:
  - 'https://jsonplaceholder.typicode.com/todos/1'
  - 'https://api.example.com/endpoint'

trigger:
- main

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  pool:
    name: ${{ parameters.agentPoolName }}
  steps:
    - bash: |
        jsonResponse=$(curl -s "${{ parameters.apiUrl }}")
        echo "JSON Response: $jsonResponse"
        echo "$jsonResponse" > $(Build.ArtifactStagingDirectory)/response.json
      displayName: 'Call GET Operation and Save Response'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'responseArtifacts'
        publishLocation: 'pipeline'

    - script: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "Pipeline Run Status: ${{ variables['Build.Reason'] }} - ${{ variables['Build.Status'] }}",
          "attachments": [
            {
              "title": "Pipeline Parameters",
              "fields": [
                {
                  "title": "Agent Pool Name",
                  "value": "${{ parameters.agentPoolName }}",
                  "short": true
                },
                {
                  "title": "API URL",
                  "value": "${{ parameters.apiUrl }}",
                  "short": true
                }
              ]
            }
          ]
        }' YOUR_WEBHOOK_URL_HERE
      displayName: 'Send Team Notification - Calling Get API'

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  pool:
    name: ${{ parameters.agentPoolName }}
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifact'
      inputs:
        artifact: 'responseArtifacts'
        path: $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      displayName: 'Copy Python Script to Staging Directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'manipulate_json.py'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - bash: |
        ls -R $(Build.ArtifactStagingDirectory)
      displayName: 'List Contents of Staging Directory'

    - bash: |
        cat $(Build.ArtifactStagingDirectory)/response.json
      displayName: 'Print Content of response.json'

    - bash: |
        /usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py
      displayName: 'Run Python Script'

    - script: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "Pipeline Run Status: ${{ variables['Build.Reason'] }} - ${{ variables['Build.Status'] }}",
          "attachments": [
            {
              "title": "Pipeline Parameters",
              "fields": [
                {
                  "title": "Agent Pool Name",
                  "value": "${{ parameters.agentPoolName }}",
                  "short": true
                },
                {
                  "title": "API URL",
                  "value": "${{ parameters.apiUrl }}",
                  "short": true
                }
              ]
            }
          ]
        }' YOUR_WEBHOOK_URL_HERE
      displayName: 'Send Team Notification - Manipulating Response'
