trigger:
- main

pool:
  name: shivamPool

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl -o $(Build.ArtifactStagingDirectory)/response.json)
        echo "JSON Response: $jsonResponse"
        
        # Debug information
        echo "Current Directory: $(System.DefaultWorkingDirectory)"
        echo "Contents of Directory: $(ls -a)"
        echo "Contents of Staging Directory: $(ls -a $(Build.ArtifactStagingDirectory))"

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Python Script and Response File'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        manipulate_json.py
        response.json
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: Bash@3
    displayName: 'List Contents of Staging Directory'
    inputs:
      targetType: 'inline'
      script: 'ls $(Build.ArtifactStagingDirectory)'

  - task: Bash@3
    displayName: 'Print Content of response.json'
    inputs:
      targetType: 'inline'
      script: 'cat $(Build.ArtifactStagingDirectory)/response.json'

  - task: Bash@3
    displayName: 'Run Python Script'
    inputs:
      targetType: 'inline'
      script: '/usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py'
