trigger:
- main

pool:
  name: shivamPool

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    displayName: 'Call GET Operation and Save Response'
    inputs:
      targetType: 'inline'
      script: |
        # Debug information
        echo "API URL: $apiUrl"

        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl -o $(Build.ArtifactStagingDirectory)/response.json) || echo "Error: Curl command failed with exit code $? and error message: $?"

        echo "JSON Response: $jsonResponse"

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'responseArtifacts'
      publishLocation: 'pipeline'

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      artifact: 'responseArtifacts'
      path: $(Build.ArtifactStagingDirectory)

  - task: Bash@3
    displayName: 'List Contents of Staging Directory'
    inputs:
      targetType: 'inline'
      script: 'ls $(Build.ArtifactStagingDirectory)'

  - task: Bash@3
    displayName: 'Print Content of response.json'
    inputs:
      targetType: 'inline'
      script: 'cat $(Build.ArtifactStagingDirectory)/response.json'

  - task: Bash@3
    displayName: 'Run Python Script'
    inputs:
      targetType: 'inline'
      script: '/usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py'
