# azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: shivam54/skanAI_repository1
      ref: main
      endpoint: shivam54  # Assuming 'shivam54' is your service connection name

variables:
- template: azure-pipelines.parameters.yml@templates

trigger:
- main

jobs:
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  pool:
    name: ${{ parameters.agentPoolName }}
  steps:
  - task: Bash@3
    displayName: 'Call GET Operation and Save Response'
    inputs:
      targetType: 'inline'
      script: |
        jsonResponse=$(curl -s "${{ parameters.apiUrl }}")
        echo "JSON Response: $jsonResponse"
        echo "$jsonResponse" > $(Build.ArtifactStagingDirectory)/response.json

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'responseArtifacts'
      publishLocation: 'pipeline'

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  pool:
    name: ${{ parameters.agentPoolName }}
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      artifact: 'responseArtifacts'
      path: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: 'Copy Python Script to Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'manipulate_json.py'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: Bash@3
    displayName: 'List Contents of Staging Directory'
    inputs:
      targetType: 'inline'
      script: 'ls -R $(Build.ArtifactStagingDirectory)'

  - task: Bash@3
    displayName: 'Print Content of response.json'
    inputs:
      targetType: 'inline'
      script: 'cat $(Build.ArtifactStagingDirectory)/response.json'

  - task: Bash@3
    displayName: 'Run Python Script'
    inputs:
      targetType: 'inline'
      script: '/usr/bin/python3 $(Build.ArtifactStagingDirectory)/manipulate_json.py'
