# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: OwaspZapScan@0
  inputs:
    zapApiUrl: 'http://localhost:9090'  # 'zapApiUrl' should be lowercase
    zapApiKey: 'shivam1234'  # 'zapApiKey' should be lowercase
    targetUrl: 'https://www.gmail.com/'  # 'targetUrl' should be lowercase
