trigger:
- main

pool:
  name: shivamPool

jobs:
- job: InstallDependencies
  displayName: 'Install Dependencies (installing jq require for manipulation)'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
    displayName: 'Install .NET SDK'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
      if ! command -v jq >/dev/null 2>&1 ; then
        sudo apt-get update
        sudo apt-get install jq -y
      else
        echo "jq is already installed."
      fi
  displayName: 'Install jq if not already installed'
  
- job: CallingGetApi
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl)
        echo "JSON Response: $jsonResponse"

- job: ManipulatingResponse
  displayName: 'Manipulating Response - Appending Timestamp and keyword "shivamData" '
  dependsOn: CallingGetApi
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        # storing response in variable 
        manipulatedResponse=$(echo $jsonResponse | jq --arg timestamp "$timestamp" '.title = "Updated Title - $timestamp shivamData"')
        
        echo "Manipulated JSON Response: $manipulatedResponse"
