trigger:
- main

pool:
  name: shivamPool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Calling the "GET" Operation 
      apiUrl="https://jsonplaceholder.typicode.com/todos/1"
      # storing response in variable
      GetjsonResponse=$(curl -s $apiUrl)
      echo "JSON Response: $GetjsonResponse"
      # Manipulate one attribute in the JSON response (e.g., update the value of "title")
     # manipulatedResponse=$(echo $jsonResponse | jq '.title = "Updated Title"')

      # Print the manipulated JSON response
     # echo "Manipulated JSON Response: $manipulatedResponse"
  displayName: 'Calling the API and fetching the response'
