# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: OwaspZapScan@0
  inputs:
    zapApiUrl: 'http://localhost:$(ProxyPort)'  # 'zapApiUrl' should be lowercase
    zapApiKey: '$(WebName)'  # 'zapApiKey' should be lowercase
    targetUrl: '$(UrlToScan)'  # 'targetUrl' should be lowercase
