trigger:
- main

pool:
  name: shivamPool

jobs:
- job: 'Calling Get Api'
  displayName: 'Calling Get API and Displaying the response'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Calling the "GET" Operation 
        apiUrl="https://jsonplaceholder.typicode.com/todos/1"
        # storing response in variable
        jsonResponse=$(curl -s $apiUrl)
        echo "JSON Response: $jsonResponse"

- job: 'Manipulating Response(Adding Timestamp)'
  displayName: 'Manipulating Response - Appending Timestamp'
  dependsOn: 'Calling Get Api'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        # storing response in variable 
        manipulatedResponse=$(echo $jsonResponse | jq --arg timestamp "$timestamp" '.title = "Updated Title - $timestamp updatedTitle"')
        
        echo "Manipulated JSON Response: $manipulatedResponse"
